export type SFSymbols6_0 = 
  | 'message.fill'
  | 'person.fill'
  | 'person.circle.fill'
  | 'envelope.fill'
  | 'bell.fill'
  | 'gear.fill'
  | 'chevron.right'
  | 'chevron.left'
  | 'xmark'
  | 'plus'
  | 'paperplane.fill'
  | 'photo.fill'
  | 'camera.fill'
  | 'mic.fill'
  | 'arrow.left'
  | 'checkmark.circle.fill'
  | 'exclamationmark.circle.fill';